Movement_System
firealarm-dev/VoxelWorld pull request #8
Opened 2022-02-26 18:21 UTC by anCreny

2022-02-26 18:39 UTC, alexthvest requested changes

2022-02-26 18:39 UTC, alexthvest commented on Assets/Scripts/MovementSystem.cs
> +    private delegate void MoveVar(float h, float v);
What does `Var` mean? Please rename delegate to be more clear

2022-02-26 18:39 UTC, alexthvest commented on Assets/Scripts/MovementSystem.cs
> +    private delegate void MoveVar(float h, float v);
Please rename parameters, `h` and `v` is not clear names

2022-02-26 18:39 UTC, alexthvest commented on Assets/Scripts/MovementSystem.cs
> +            _gameObject.GetComponent<Rigidbody>().AddForce(Vector3.up * _jumpForce);
As I know, `GetComponent` is complex operation, you should get it only once in constructor

2022-02-26 18:39 UTC, alexthvest commented on Assets/Scripts/MovementSystem.cs
> +        var speed = _speed;
Please use `? : ` operator, like this

```csharp
var speed = InSprint ? _sprintSpeed : _speed;
```

2022-02-26 18:39 UTC, alexthvest commented on Assets/Scripts/PlayerBehavior.cs
> +    void Awake()
Please always specify access modifiers. Also please format this file

2022-02-26 18:46 UTC, anCreny commented on Assets/Scripts/PlayerBehavior.cs
> +    void Awake()
> Please always specify access modifiers. Also please format this file

What's mean format file?

2022-02-26 19:07 UTC, alexthvest commented on Assets/Scripts/PlayerBehavior.cs
> +    void Awake()
Add spacing between methods and some other things to beautify code

2022-05-10 14:23 UTC, alexthvest requested changes

2022-05-10 14:23 UTC, alexthvest commented on Assets/Scripts/CameraSystem.cs
> +        _targetTransform = target.GetComponent<Transform>();
Please pass target's Transform into constructor instead whole target. So we need just transform

2022-05-10 14:23 UTC, alexthvest commented on Assets/Scripts/CameraSystem.cs
> +        _cameraTransform = GameObject.FindGameObjectWithTag("MainCamera").GetComponent<Transform>();
Same here, can we pass camera transform outside. 
Also finding camera by string tag is not safety, I guess. May be passing camera into script via property will be more suitable.

2022-05-10 14:23 UTC, alexthvest commented on Assets/Scripts/CameraSystem.cs
> +
Please format code

2022-05-10 14:23 UTC, alexthvest commented on Assets/Scripts/CameraSystem.cs
> +        }else if (vPart != 0)
Format code

2022-05-10 14:23 UTC, alexthvest commented on Assets/Scripts/PlayerBehavior.cs
> +    private void OnTriggerEnter(Collider other)
Please format code, follow indents and blank lines

2022-05-10 14:23 UTC, alexthvest commented on Assets/Scripts/PlayerBehavior.cs
> +    private void OnTriggerEnter(Collider other)
Please format code following indents and blank lines

2022-05-10 14:23 UTC, alexthvest commented on Assets/Scripts/PlayerBehavior.cs
> +    private void OnTriggerEnter(Collider other)
Please format code following indents and blank lines

2022-05-10 14:23 UTC, alexthvest commented on Packages/manifest.json
> +    "com.unity.cinemachine": "2.6.11",
Is this package used in your code? Should we remove it?

2022-05-10 15:48 UTC, anCreny commented on Packages/manifest.json
> +    "com.unity.cinemachine": "2.6.11",
unfortunately, it's the package for moving camera properly with mouse. It's the plug-in.

2022-05-10 16:22 UTC, anCreny commented on Assets/Scripts/CameraSystem.cs
> +        }else if (vPart != 0)
I can't do it. I need this part of code and don't see another way to realize it.

2022-05-10 16:26 UTC, anCreny commented on Packages/manifest.json
> +    "com.unity.cinemachine": "2.6.11",
It isn't used actually in code, but it's used in the Scene to let you move the camera properly with a mouse.

2022-05-10 16:52 UTC, anCreny commented on Assets/Scripts/CameraSystem.cs
> +        _cameraTransform = GameObject.FindGameObjectWithTag("MainCamera").GetComponent<Transform>();
Yeah, I can move it in PlayerBehavior.cs or in a property but I can't find an another way to get CameraTransform insted of using actual string (FindGameObjectWithTag and FindWithTag) or public fields. Please tell me the way to avoid using the string and public fields in case you know it.

2022-05-10 17:05 UTC, anCreny commented on Assets/Scripts/CameraSystem.cs
> +        _cameraTransform = GameObject.FindGameObjectWithTag("MainCamera").GetComponent<Transform>();
Also, I guess, getting camera transform should be in CameraSystem.cs because only CameraSystem.cs is responsible for camera transform

2022-05-11 06:18 UTC, alexthvest commented on Assets/Scripts/CameraSystem.cs
> +        _cameraTransform = GameObject.FindGameObjectWithTag("MainCamera").GetComponent<Transform>();
Use private fields with `SerializeField` attribute

2022-05-16 11:06 UTC, alexthvest approved these changes

2022-05-16 11:06 UTC, merged